POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vam8iLCJpZCI6IjVhODg0YjM2Mzc2YjFmMWExOTQ5NDhhNSIsImlhdCI6MTUxODg4MzAxOH0.HXAyYXKzcWFlibbqx64mke7pvouHatsYil3ADzGGQYo

{
  "title": "Blogi",
  "author": "Authori",
  "url": "https://blog.fi",
  "likes": 0,
  "userId": "5a86da0c57886f6b2543f9f7"
}